# see https://packaging.python.org/appveyor/#adding-appveyor-support-to-your-project
environment:
  # For Python versions available on Appveyor, see
  # http://www.appveyor.com/docs/installed-software#python
  # The list here is complete (excluding Python 2.6, which
  # isn't covered by this document) at the time of writing.
  PYTHON: "C:\\Python34-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pyqt5 pyinstaller"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  
build_script:
  - "%PYTHON%\\python.exe -m PyInstaller -y ayab.spec"
  - 7z a -tzip ayab-windows.zip "dist/ayab/*"
  - cmd: cmd /c "windows-build\\Inno Setup 5\\ISCC.exe" windows-build\\ayab.iss

artifacts:
- path: ayab-windows.zip
  name: standalone
- path: windows-build/AYABInstaller.exe
  name: installer
